easy_admin:
    site_name: Loose Reins
    design:
        brand_color: "#a1c349"
        assets:
            css: []

    list:
        title: '%%entity_label%%'
        actions: ['show']
    entities:
        # List the entity class name you want to manage
        Homepage:
            class: App\Entity\Homepage
            form:
                fields:
                    - 'title'
                    - {property: 'headerContent', type: 'fos_ckeditor'}
                    - 'boxOneImage'
                    - {property: 'boxOneContent', type: 'fos_ckeditor'}
                    - 'boxTwoImage'
                    - {property: 'boxTwoContent', type: 'fos_ckeditor'}
        Navigation:
            class: App\Entity\Navigation
#        MainPage:
#            class: App\Entity\MainPage
#            label: Navigation
#            help: 'Here are the main navigation links for the site'
#            list:
#                help: 'Here are all the main navigation links for the site'
#        Page:
#            class: App\Entity\Page
#            label: Sub Nav/Pages
#            list:
#                title: Sub Navigation/Pages
        Page:
            class: App\Entity\Page
        Panel:
            class: App\Entity\Panel
            form:
                fields:
                    - 'id'
                    - {property: 'content', type: 'fos_ckeditor'}
                    - 'image'
                    - 'weight'
                    - 'layout'
                    - 'page'

