easy_admin:
    site_name: Loose Reins
    design:
        brand_color: "#a1c349"
        assets:
            css: []
        menu:
            - {entity: 'Homepage', icon: 'home'}
            - {entity: 'Navigation', icon: 'link'}
            - {entity: 'Article', icon: 'sticky-note'}
            - {entity: 'Page', icon: 'sticky-note'}
            - {entity: 'Panel', icon: 'table'}
            - {entity: 'ContactUs', icon: 'envelope', label: 'Contact'}

    list:
        title: '%%entity_label%%'
        actions: ['show']
    entities:
        # List the entity class name you want to manage
        Homepage:
            class: App\Entity\Homepage
            form:
                fields:
                    - 'title'
                    - {property: 'headerContent', type: 'fos_ckeditor'}
                    - 'boxOneImage'
                    - {property: 'boxOneContent', type: 'fos_ckeditor'}
                    - 'boxTwoImage'
                    - {property: 'boxTwoContent', type: 'fos_ckeditor'}
        Navigation:
            class: App\Entity\Navigation
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'parent'
                    - {property: 'navigations', label: 'Child Links'}
                    - 'page'
                sort: ['parent.title', 'ASC']
            new:
                fields:
                    - 'title'
                    - 'parent'
                    - 'navigations'
                    - 'page'
            edit:
                fields:
                    - 'title'
                    - 'parent'
                    - 'navigations'
                    - 'page'
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - 'title'
                    - 'primaryImage'
                    - 'secondaryImage'
                    - 'summary'
                    - {property: 'content', type: 'fos_ckeditor'}
                    - 'isPublished'
        Page:
            class: App\Entity\Page
            form:
                fields:
                    - 'title'
                    - 'image'
                    - 'navigation'
                    -
                        property: 'panels'
                        type: 'collection'
                        type_options:
                            entry_type: App\Form\PanelFormType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
        Panel:
            class: App\Entity\Panel
            form:
                fields:
                    - {property: 'content', type: 'fos_ckeditor'}
                    - {property: 'image'}
                    - 'weight'
                    - { property: 'layout', type: 'choice', type_options: {choices: {'Image with text box overlay':'image-text-overlay', 'Text box with image 50/50 ':'image-text-split'}}}
                    - 'page'
            list:
                fields:
                    - 'id'
                    - 'page'
                    - 'layout'
                    - 'weight'
                    - {property: 'image', type: image}
        ContactUs:
            class: App\Entity\ContactUs
            list:
                title: 'Contact'
                help: 'List of emails received'
                fields:
                    - 'id'
                    - 'name'
                    - 'email'
                    - 'message'
                    - {property: 'subscribe', type: 'boolean', label: 'Subscribed'}
                    - {property: 'createdAt', label: 'Received at'}
            edit:
                fields:
                    - 'name'
                    - 'email'
                    - 'message'
                    - 'subscribe'